### ISSUE TITLE
Does this work for private goo.gl, i.e. links tracked by your own google account

### ISSUE THREAD

**Issue by gbcox** [averissimo/shorten-me#2]
All my links are under my google account - I setup the api key, but the links aren't showing up under my account.  Does something else need to be done?  I was using this under chrome:
https://chrome.google.com/webstore/detail/url-shortener-lite-with-g/mnnkfmkiefebamlmijhohmjaajilnlen
which works fine - but unfortunately it hasn't been ported to Fx.

Thanks!

**Comment by averissimo** [comment]
thanks for reporting, I'll test this scenario.

**Comment by averissimo** [comment]
I've just tested using a private key I have and below is the description on my steps.

**Can you explain if you did something differently?** 

1. Open the extensions options by going to `about:addons` and double clicking on `shorten-me`
1. Insert my private key created from https://console.developers.google.com/apis/dashboard
1. Click `save`
1. Open a new tab
1. Click on Toolbar button
1. Check traffic in Api Dashboard -- https://console.developers.google.com/apis/dashboard
    - The peak in the screenshot are the two tests I did.

![image](https://user-images.githubusercontent.com/211358/34184818-c5d10d64-e519-11e7-903d-cf8f1bb657fe.png)
