### ISSUE TITLE
stopped working today

### ISSUE THREAD

**Issue by Robbie711** [averissimo/shorten-me#6]
Hi Andre,

Getting the "Oops, something went wrong, Sorry" error
Error on all pages, not just Amazon.

Do you have a debugger log?

V2.0.5 
Last Updated March 28, 2020
FF 74.0

**Comment by averissimo** [comment]
It has reached the maximum of the bit.ly account

I updated that day with new account and hope to create a system that allows for current users and more growth.

It should've worked since the update. And I believe it works now.

Sorry for that.

**Comment by Robbie711** [comment]
Thank you, Andre, it works now. You are a very responsible developer. Do you have a PayPal account for me to make a donation, perhaps for a cup of Starbucks if you have one in Portugal? 

Robbie

**Comment by HelArcherix** [comment]
it shows again "Oops, something went wrong, Sorry"

**Comment by averissimo** [comment]
Extension is back working since v3.0.0 released 2 days ago.

v3.0.2 removes preference and cleans-up some old APIs

Thanks for reporting!
