### ISSUE TITLE
QR Code not displaying

### ISSUE THREAD

**Issue by DavyRay** [averissimo/shorten-me#8]

**Comment by averissimo** [comment]
Can you elaborate on this?

AFAIK the addon doesn't generate the QR code.

**Comment by DavyRay** [comment]
It was an error on my part.  I have 2 similar extensions and I contacted you by mistake.  I tried to delete the post, but it would not allow me, so I tried to edit it to erase the contents.  I am sorry about that.

**Comment by averissimo** [comment]
No problem!
